server:
  port: 8080

spring:
  redis:
    database: 0
    host: 124.71.38.83
    port: 6379
    password: tt19950826tt
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

